version: '2.1'

jobs:
  build:
    docker:
      # https://github.com/CircleCI-Public/cimg-openjdk
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          # pom.xmlをchache用にコピー。pom.xmlが存在しないときにエラーにするためにわざわざコピーしている
          # https://circleci.com/developer/orbs/orb/circleci/maven#orb-source
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: 'mvn clean package'
      - save_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
          paths:
            - ~/.m2/repository
      #      - store_test_results:
      #          path: target/surefire-reports
      - run:
            name: Compress Artifacts
            command: mkdir -p crud-test/lib; cp -p ~/project/gui/target/*.jar crud-test/lib/;  cp -p ~/project/core/target/*.jar crud-test/lib/; cp -p ~/project/start.bat crud-test/; zip -r crud-test crud-test/
      - store_artifacts:
          path: crud-test.zip
#      - store_artifacts:
#          path: ~/project/gui/target/*.jar
#      - store_artifacts:
#          path: ~/project/core/target/*.jar
#      - store_artifacts:
#          path: ~/project/start.bat

workflows:
  jar-build:
    jobs:
      - build
