#!/bin/bash

JAVA_HOME=

DB_URL="jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)))"
DB_USER="TEST"
DB_PASS="pass2"


BASE_DIR=
CLASS_PATH=
JAR_NAME=
LOG_FILE="./app.log"


